M48
; DRILL file {KiCad 7.0.6} date Thu Feb 29 16:34:34 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-29T16:34:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C2.000
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C2.900
%
G90
G05
T1
X-11.3Y3.0
X-3.0Y-2.75
X-1.0Y-2.75
X1.0Y-2.75
X3.0Y-2.75
X11.3Y-3.0
T2
X-11.1Y5.95
X-11.1Y-5.95
X11.1Y4.45
X11.1Y-5.95
T3
X-12.0Y0.0
X12.0Y0.0
T0
M30
